EXECUTE BLOCK AS
  DECLARE VARIABLE NEXT_ID BIGINT;
  DECLARE VARIABLE EMPRESA_NOME VARCHAR(120);
BEGIN
  SELECT COALESCE(MAX(ID), 0)
  FROM EMPRESAS_BACKUP_MONITORADAS
  INTO :NEXT_ID;

  FOR
    SELECT DISTINCT TRIM(log.EMPRESA)
    FROM BACKUP_UPLOAD_LOG log
    WHERE log.EMPRESA IS NOT NULL
      AND TRIM(log.EMPRESA) <> ''
      AND NOT EXISTS (
        SELECT 1
        FROM EMPRESAS_BACKUP_MONITORADAS monitoradas
        WHERE monitoradas.EMPRESA = TRIM(log.EMPRESA)
      )
    ORDER BY 1
    INTO :EMPRESA_NOME
  DO
  BEGIN
    NEXT_ID = NEXT_ID + 1;

    INSERT INTO EMPRESAS_BACKUP_MONITORADAS (
      ID,
      EMPRESA,
      ATIVO,
      OBRIGA_BACKUP,
      HORAS_LIMITE_SEM_BACKUP,
      EXIBIR_ALERTA
    ) VALUES (
      :NEXT_ID,
      :EMPRESA_NOME,
      'S',
      'S',
      24,
      'S'
    );
  END
END;
