EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$RELATIONS
    WHERE RDB$RELATION_NAME = 'USUARIOS_PAINEL'
  )) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TABLE USUARIOS_PAINEL (
        ID BIGINT NOT NULL,
        NOME VARCHAR(120) NOT NULL,
        LOGIN VARCHAR(60) NOT NULL,
        SENHA_HASH VARCHAR(255) NOT NULL,
        ATIVO CHAR(1) DEFAULT ''S'',
        CONSTRAINT PK_USUARIOS_PAINEL PRIMARY KEY (ID)
      )
    ';
  END
END;
