EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'BACKUP_UPLOAD_LOG'
      AND TRIM(RDB$FIELD_NAME) = 'REVISADO'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'ALTER TABLE BACKUP_UPLOAD_LOG ADD REVISADO CHAR(1)';
  END

  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'BACKUP_UPLOAD_LOG'
      AND TRIM(RDB$FIELD_NAME) = 'DATA_HORA_REVISAO'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'ALTER TABLE BACKUP_UPLOAD_LOG ADD DATA_HORA_REVISAO TIMESTAMP';
  END

  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'BACKUP_UPLOAD_LOG'
      AND TRIM(RDB$FIELD_NAME) = 'USUARIO_REVISAO'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'ALTER TABLE BACKUP_UPLOAD_LOG ADD USUARIO_REVISAO VARCHAR(120)';
  END

  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'BACKUP_UPLOAD_LOG'
      AND TRIM(RDB$FIELD_NAME) = 'OBS_REVISAO'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'ALTER TABLE BACKUP_UPLOAD_LOG ADD OBS_REVISAO VARCHAR(500)';
  END
END;
