EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$RELATIONS
    WHERE RDB$RELATION_NAME = 'EMPRESAS_BACKUP_MONITORADAS'
  )) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TABLE EMPRESAS_BACKUP_MONITORADAS (
        ID BIGINT NOT NULL,
        EMPRESA VARCHAR(120) NOT NULL,
        ATIVO CHAR(1) DEFAULT ''S'',
        OBRIGA_BACKUP CHAR(1) DEFAULT ''S'',
        HORAS_LIMITE_SEM_BACKUP INTEGER DEFAULT 24,
        EXIBIR_ALERTA CHAR(1) DEFAULT ''S'',
        OBSERVACAO VARCHAR(500),
        DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT PK_EMPRESAS_BACKUP_MONITORADAS PRIMARY KEY (ID)
      )
    ';
  END
END;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$INDICES
    WHERE RDB$INDEX_NAME = 'UX_EMP_BACKUP_MON_EMPRESA'
  )) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE UNIQUE INDEX UX_EMP_BACKUP_MON_EMPRESA
      ON EMPRESAS_BACKUP_MONITORADAS (EMPRESA)
    ';
  END
END;
